### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by Aizazahmed-7** [npms-io/npms-api#115]

**Comment by sebastian-adam** [comment]
Still an issue. Receiving a 522 for GET requests to all tested endpoints including but not limited to `https://api.npms.io/v2/search/suggestions`

**Comment by sebastian-adam** [comment]
For additional context into the scope of the issue, https://npms.io/ is offline with an error code of 521. The following screenshot was taken in Chicago. Happy to provide more diagnostics if I can, though Cloudfare is failing the requests due to no-response timeouts and I don't think I have access to anything more helpful.

![Screen Shot 2024-04-14 at 1 55 43 PM](https://github.com/npms-io/npms-api/assets/19532408/8dbf5200-e8d9-476d-bb97-b3d19d6d8a2e)

**Comment by satazor** [comment]
It's back up. The machine had an issue with the bootscript and had to be decommissioned.
