### ISSUE TITLE
Add qualifier to find packages which do not contain a keyword

### ISSUE THREAD

**Issue by ekaragodin** [npms-io/npms-api#50]
For example I want to find all hyperterm related packages but skip hyperterm themes: `keywords:hyperterm,-hyperterm-theme`.

**Comment by satazor** [comment]
That would be really easy to implement, perhaps you could do a PR?

Create a `normalizeKeywords` function here: https://github.com/npms-io/npms-api/blob/master/lib/util/parseQuery.js#L60 that basically parses the keywords and replaces the string with an object with `{ include: 'hyperterm', exclude: 'hyperterm-theme' }`. Then  update https://github.com/npms-io/npms-api/blob/master/lib/routes/search/query.js#L87 to add `keywords.include` to `must` and `keywords.exclude` to `mustNot`.

I can send you a link of elasticsearch data so that you can test this out.
